// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6847kAzR4NmB7sNxqrEKRlgrFDA1iXq8',
    appId: '1:808980544496:web:0cceb2e9cc6b0e312efb35',
    messagingSenderId: '808980544496',
    projectId: 'chatapp-3c8eb',
    authDomain: 'chatapp-3c8eb.firebaseapp.com',
    storageBucket: 'chatapp-3c8eb.firebasestorage.app',
    measurementId: 'G-0JE2CVNVH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NN_Uk3zxYcd3QQRGWGDxhYv62qEJIAQ',
    appId: '1:808980544496:android:7d80d2eee5d9d6c92efb35',
    messagingSenderId: '808980544496',
    projectId: 'chatapp-3c8eb',
    storageBucket: 'chatapp-3c8eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASoJDFYg8q8PZwsM_oerbKk-MUaIxflGA',
    appId: '1:808980544496:ios:e05bcf859641f35c2efb35',
    messagingSenderId: '808980544496',
    projectId: 'chatapp-3c8eb',
    storageBucket: 'chatapp-3c8eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASoJDFYg8q8PZwsM_oerbKk-MUaIxflGA',
    appId: '1:808980544496:ios:e05bcf859641f35c2efb35',
    messagingSenderId: '808980544496',
    projectId: 'chatapp-3c8eb',
    storageBucket: 'chatapp-3c8eb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6847kAzR4NmB7sNxqrEKRlgrFDA1iXq8',
    appId: '1:808980544496:web:bc79615614710cac2efb35',
    messagingSenderId: '808980544496',
    projectId: 'chatapp-3c8eb',
    authDomain: 'chatapp-3c8eb.firebaseapp.com',
    storageBucket: 'chatapp-3c8eb.firebasestorage.app',
    measurementId: 'G-K55BX0CNQD',
  );
}
